### ISSUE TITLE
[Android Only] App crash when close modal crisp chat.

### ISSUE THREAD

**Issue by khanhkom** [walterholohan/react-native-crisp-chat-sdk#110]
- My app was crash when i close modal crisp. I am using "react-native-crisp-chat-sdk": "^0.10.2" . 
- Here is crash log:
 FATAL EXCEPTION: main
                                                                                                    Process: vn.com.eatsy, PID: 11421
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/Player$EventListener;
                                                                                                    	at im.crisp.client.internal.utils.b.a(Unknown Source:0)
                                                                                                    	at im.crisp.client.Crisp.d(Unknown Source:0)
                                                                                                    	at im.crisp.client.ChatActivity.onDestroy(Unknown Source:3)
                                                                                                    	at android.app.Activity.performDestroy(Activity.java:8203)
channel 'e3aaa7c vn.com.eatsy/im.crisp.client.ChatActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
channel 'fc6db7 vn.com.eatsy/vn.com.eatsy.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
packageMonitor   onPackageModified  packageName=vn.com.eatsy   mIsRecentsWithinLauncher=true
packageMonitor   onPackageModified  packageName=vn.com.eatsy   mIsRecentsWithinLauncher=true

**Comment by baptistejamin** [comment]
Hello!

The SDK got updated, you shoulnt note have this error anymore
