### ISSUE TITLE
Android: Exoplayer MultiDex Crash

### ISSUE THREAD

**Issue by ZComwiz** [walterholohan/react-native-crisp-chat-sdk#46]
Following the instructions:

`import im.crisp.client.Crisp;

// Fixes multiDex error
import androidx.multidex.MultiDexApplication;

public class MainApplication extends MultiDexApplication implements ReactApplication {
...
`

results in a crash where Exoplayer path cannot be found at runtime. Using React Native 64. Adding implementation in gradle for Exoplayer 2 13 does nothing to improve the issue.

`   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.drm.DefaultDrmSessionEventListener" on path: DexPathList[[zip file "/data/app/com.<APPNAME>-8zolvrwpAJkqGhXfmrSMxg==/base.apk"],nativeLibraryDirectories=[/data/app/com.<APPNAME>-8zolvrwpAJkqGhXfmrSMxg==/lib/arm64, /data/app/com.<APPNAME>-8zolvrwpAJkqGhXfmrSMxg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:42) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:857) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:196) 
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:161) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147) 
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191) 
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156) 
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:149) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:488) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:464) 
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:91) 
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46) 
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1142) 
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1090) 
        at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:131) 
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1044) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:237) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:919) 
2021-11-10 12:13:58.479 13419-13569/com.<APPNAME> E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.<APPNAME>, PID: 13419
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/drm/DefaultDrmSessionEventListener;
        at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:42)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:857)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:196)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:161)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:149)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:488)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:464)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:91)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46)
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1142)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1090)
        at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1044)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.drm.DefaultDrmSessionEventListener" on path: DexPathList[[zip file "/data/app/com.<APPNAME>-8zolvrwpAJkqGhXfmrSMxg==/base.apk"],nativeLibraryDirectories=[/data/app/com.<APPNAME>-8zolvrwpAJkqGhXfmrSMxg==/lib/arm64, /data/app/com.<APPNAME>-8zolvrwpAJkqGhXfmrSMxg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:42) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:857) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:196) 
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:161) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147) 
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191) 
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156) 
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:149) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:488) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:464) 
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:91) 
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46) 
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1142) 
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1090) 
        at com.facebook.react.ReactInstanceManager.access$1500(ReactInstanceManager.java:131) 
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1044) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:237) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:919) `

Any suggestions @walterholohan ?

**Comment by Anandhu5** [comment]
Am also facing this issue , Any update or workaround for this one!

**Comment by baptistejamin** [comment]
Hello!

Do you still have this issue?
